name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

env:
  SN_RELEASE: fast

jobs:
  unix_build:
    name: Unix build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - uses: coursier/setup-action@v1

      - run: |
          brew install protobuf && \
          brew install swift-protobuf

      - run: ./mill buildMacos

