name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

env:
  SN_RELEASE: fast

jobs:
  unix_build:
    name: Unix build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - uses: coursier/setup-action@v1
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
        with:
          power: true

      - run: |
          brew install protobuf && \
          brew install swift-protobuf && \
          curl -Lo protoc-gen-scala.zip https://github.com/scalapb/ScalaPB/releases/download/v0.11.14/protoc-gen-scala-0.11.14-osx-x86_64.zip &&\
          unzip protoc-gen-scala.zip && \
          mv protoc-gen-scala /usr/local/bin/protoc-gen-scala && \
          brew install llvm@14
      - run: ./mill buildMacos

